version: '3.7'

services:
   postgres-db:
      container_name: "pgsql"
      restart: always
      image: postgres:10
      volumes:
         - ./base-pgsql-cicd.sql:/docker-entrypoint-initdb.d/database.sql
         - db:/var/lib/postgresql/data
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_USER=user
         - POSTGRES_PASSWORD=password

      networks:
         - lan
   app-quode:
      restart: always
      container_name: "app-quode"
      image: app-quode-teste
      ports: 
         - "8181:8500"
      networks:
          - lan
networks:
  lan:
    driver: bridge
volumes:
  db:
    driver: local